### ISSUE TITLE
MongoDB Setup-Script: MongoDB 6.x no longer runs on macOS Ventura Version 13.1

### ISSUE THREAD

**Issue by ahohnsen** [neuefische/web-setup#4]
I tried the **MongoDB setup script** on my Macbook (M1, macOS Ventura 13.1) and got the following error:

<img width="1422" alt="Screenshot 2023-01-13 at 17 05 49" src="https://user-images.githubusercontent.com/94636438/212369878-91f4cbe1-eec3-49d3-8a38-a547028074a0.png">

Afterwards I got the following error connecting to `mongodb://localhost:27017` via MongoDB Compass:

> ECONNREFUSED 127.0.0.1:27017

@JessicaLoers found [this article](https://www.mongodb.com/community/forums/t/mongodb-6-x-no-longer-runs-on-macos-ventura-version-13-1-22c65/204977), which states that MongoDB 6.x does not longer run on macOS _Ventura Version 13.1_.

We fixed this issue by uninstalling `mongodb-community` and installing `mongodb-community@5.0` instead.
As our students might update to _Ventura_, I think it would be good to address this issue in the **MongoDB setup script**.

**Comment by mpagels** [comment]
I've investigated that problem. 

It seems that the problem that is linked in the article is not related to our problem. 
And it is not an article, by the way, it is a normal forum entry in the mongo community ;-) with an unfortunately misleading title. <- And this sentence reads meaner than intended. But I don't know how I could have put it differently in the language.

And it seems, that the problem in there is solved as well. They tried to install `mongo community 6.0.1` what was recently updated to `mongo-community 6.0.3` and everything seems to work now.

The root of **our** problem might be, that an instance of mongo is already running after the installation. Why? I don't know, there are a lot of possibilities here.

I would suggest, before downgrading the version and having two scripts, trying installing mongo version `6.0.3` again and try to fix the problem by:

- [ ]  stop the mongo server services
- [ ] delete the current mongo version on your system (like everything) 
- [ ] run the script with the 6.0.3 version again
- [ ] and then read this [stackoverflow question](https://stackoverflow.com/questions/68975769/brew-services-cant-start-service-get-bootstrap-failed-5-input-output-error). The problem is solved there.

I'm very happy to help and get mongo `6.0.3` up and running. Feel free to contact me.
Might be a shot, to work with the latest version of mongo, instead of installing the old one.

**Comment by mpagels** [comment]
Might be interesting for others how you did it. Because I did not remember the commands, you did. I was really impressed.

**List the software via brew**
```
brew list
```

**delete mongo software via brew command**
```
brew delete mongodb-community
```
```
brew delete mongodb-database-tools
```
```
brew delete mongodb-compass
```

**Comment by ahohnsen** [comment]
And to stop the mongo server services:

```
brew services stop mongodb-community
```
